Rename typeIdentifier to dataType and fix the naming of our constants
material-foundation/material-remixer-ios pull request #70
Opened 2016-12-14 20:34 UTC by chuga

2016-12-14 22:09 UTC, chriscox requested changes

2016-12-14 22:09 UTC, chriscox commented on src/core/UI/RMXOverlayViewController.m
> +  } else if ([variable.controlType isEqualToString:RMXControlTypeColorPicker]) {
Shouldn't this actually be changed to `RMXControlTypeColorInput`?

2016-12-14 22:09 UTC, chriscox commented on src/core/UI/RMXOverlayViewController.m
> +  } else if ([variable.controlType isEqualToString:RMXControlTypeTextPicker]) {
This should be `RMXControlTypeTextList`?

2016-12-14 22:09 UTC, chriscox commented on src/core/remixes/private/RMXVariableConstants.h
> +static NSString *const RMXControlTypeColorPicker = @"__ControlTypeColorPicker__";
`static NSString *const RMXControlTypeColorColorInput = @"__ControlTypeColorInput__";`

2016-12-14 22:09 UTC, chriscox commented on src/core/remixes/private/RMXVariableConstants.h
> +static NSString *const RMXControlTypeTextPicker = @"__ControlTypeTextPicker__";
static NSString *const RMXControlTypeTextList = @"__ControlTypeTextList__";

2016-12-15 16:39 UTC, chuga commented on src/core/UI/RMXOverlayViewController.m
> +  } else if ([variable.controlType isEqualToString:RMXControlTypeColorPicker]) {
Done

2016-12-15 16:39 UTC, chuga commented on src/core/UI/RMXOverlayViewController.m
> +  } else if ([variable.controlType isEqualToString:RMXControlTypeTextPicker]) {
Done

2016-12-15 16:39 UTC, chuga commented on src/core/remixes/private/RMXVariableConstants.h
> +static NSString *const RMXControlTypeColorPicker = @"__ControlTypeColorPicker__";
Done

2016-12-15 16:39 UTC, chuga commented on src/core/remixes/private/RMXVariableConstants.h
> +static NSString *const RMXControlTypeTextPicker = @"__ControlTypeTextPicker__";
Done

2016-12-15 17:22 UTC, chriscox approved these changes

2016-12-15 17:59 UTC, merged